# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{async-proxy}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Angel Faus"]
  s.date = %q{2010-09-12}
  s.description = %q{turn any object into an async version of itself, so that all method calls will run asynchronously, including dependent computations}
  s.email = %q{angel@vlex.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "async-proxy.gemspec",
     "lib/async-proxy.rb",
     "lib/computed_proxy.rb",
     "lib/init.rb",
     "lib/object_extensions.rb",
     "lib/object_proxy.rb",
     "spec/async-proxy_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/angelf/async-proxy}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{run any method call asynchronously without caring about threads}
  s.test_files = [
    "spec/async-proxy_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if RUBY_VERSION >= '1.9'
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_runtime_dependency(%q<Timeout>, [">= 0"])
    else
      if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
        s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
        s.add_runtime_dependency(%q<SystemTimer>, [">= 0"])
      else
        s.add_dependency(%q<rspec>, [">= 1.2.9"])
        s.add_dependency(%q<SystemTimer>, [">= 0"])
      end
    end
  else
    if RUBY_VERSION >= '1.9'
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<Timeout>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<SystemTimer>, [">= 0"])
    end
  end
end

